### ISSUE TITLE
Catch and Report errors (generally and esp with loading data package data)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#133]
At the moment no data shows up on https://staging.datapackaged.com/core/co2-ppm -- see #121 

Whilst we can fix this specific issue, it highlights that we need to report to the user when something has worked.

## Tasks

* [ ] Determine how we can catch errors
* [ ] Decide how best to report this
* [ ] Implement

**Comment by rufuspollock** [comment]
Not a priority atm.

**Comment by zelima** [comment]
WONTFIX/OBSOLETE right now if the latest revision is not successful we are showing the one that was and displaying error report on the revision page. Eg:

If one published dataset 5 times and last 2 attempts failed due to whatever reason, showcase page will show revision N3, and will display error messages for revision N4 and N5 on dedicated pages.

* https://datahub.io/core/co2-ppm -> will show data from revision 3
* https://datahub.io/core/co2-ppm/v/4 and https://datahub.io/core/co2-ppm/v/5 will display error report
