### ISSUE TITLE
Reimplement `datapackage-test` library for creating Table object and reading it

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#88]
Previously we have had to workaround [a bug][bug] in `datapackage-test` library by using `jts` directly for creating Table object and reading resource. Now, the bug is fixed upstream and we can use the library directly again.

[bug]: https://github.com/frictionlessdata/datapackage-js/issues/52

## Tasks

* [x] Revert code in redux actions to use library directly (make sure we have test - think we do already)

**Comment by rufuspollock** [comment]
It turns out we don't have a test since the actions tests were commented out by @subhankarb https://github.com/frictionlessdata/dpr-js/commit/68c45333c0089329d2cdd2a25f3b319539211e2d.

I've tried reinstating but there is quite a lot going on (much of which may be outdated). For now, I'm just going to implement the change to new `datapackage` and hope for the best -- the change is minor.
